### ISSUE TITLE
Responsive Header Title

### ISSUE THREAD

**Issue by ulken** [jameskoster/highwind#18] opened 2013-10-20 19:35 UTC
I've posted [this](http://wordpress.org/support/topic/search-widget-and-mobile-theme) on the theme's support forum, but have not received any response, so figured I'd try here. 

The issues lies in the header title not being proportionate (stemming from h1 font size being fixed) to the screen width which results in the header title being wrapped on smaller screens, as seen below:

![Wrapped header title](https://f.cloud.github.com/assets/516549/1368756/de9a8260-39bc-11e3-9a61-1d4e13931b7c.png)
**Note**: _Lamahjälpen_ is _one_ word

**Suggestion**
I see you already include fitVids.js, and my suggestion is to incorporate something like [FitText.js](http://fittextjs.com) or [FlowType.js](http://simplefocus.com/flowtype) to apply something similar to typography.

If you feel that is too heavy or something, at least some media queries to adjust the font size according to screen width would be desirable.

Thank you very much for a beautiful, functional theme!

PS. I use it on a (basic) [wordpress.com](http://wordpress.com) blog, which is why I can't make the necessary changes myself.

**Comment by jameskoster** [comment] 2013-10-21 08:31
Hey,

You will need to post this on the .com forums. The .org and .com versions of this theme are quite different ( it was re-written for .com so I can't really help you there ).

In a recent update to the .org version I addressed this by reducing heading font sizes on small screens. Maybe ask the .com folks to update the .com version of the theme?

Closing this regardless as it's not a bug in this particular version :)

**Closed as completed by jameskoster** 2013-10-21 08:31 UTC

**Comment by ulken** [comment] 2013-10-21 08:37
OK, fair enough. Not sure who to contact (or where), though. Do you know who is responsible or where to turn?

Thank you.

**Comment by jameskoster** [comment] 2013-10-21 08:43
I don't have much experience with .com so I'm not sure either. I guess the place to start would be here http://en.support.wordpress.com/ :-)

**Comment by ulken** [comment] 2013-10-21 09:08
Yeah, that's what I figured, but it seemed a little messy to me. All kinds of support topics mixed in the same forum. Oh, well, found a seemingly active thread about the theme, so took a shot there!

Thanks again!
